### ISSUE TITLE
`Jbuilder` not being loaded for isolated packages

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/jbuilder-schema#23]
I was trying to run unit tests for `bullet_train-super_scaffolding` when I ran into this error.

I added `gem "jbuilder"` to the Gemfile and ran `bundle install`, but still got the same thing.

I ended up adding `require "jbuilder"` to [jbuilder-schema/lib/jbuilder/schema.rb](https://github.com/bullet-train-co/jbuilder-schema/blob/main/lib/jbuilder/schema.rb) and that solved the problem, but I haven't worked with this gem enough to know if that's a valid solution or not.

```
/Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jbuilder-schema-2.0.3/lib/jbuilder/schema.rb:7:in `<top (required)>': uninitialized constant Jbuilder (NameError)
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bullet_train-api-1.1.15/lib/bullet_train/api.rb:13:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bullet_train-api-1.1.15/lib/bullet_train/api.rb:13:in `<top (required)>'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:79:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:79:in `rescue in block in require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:57:in `block in require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/dummy/config/application.rb:7:in `<top (required)>'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/dummy/config/environment.rb:2:in `require_relative'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/dummy/config/environment.rb:2:in `<top (required)>'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/test_helper.rb:4:in `require_relative'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/test_helper.rb:4:in `<top (required)>'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/lib/scaffolding/block_manipulator_test.rb:1:in `require'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/lib/scaffolding/block_manipulator_test.rb:1:in `<top (required)>'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `each'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `load_tests'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:40:in `run'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine/commands.rb:9:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine/commands.rb:9:in `<top (required)>'
	from bin/rails:14:in `require'
	from bin/rails:14:in `<main>'
/Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:66:in `require': cannot load such file -- bullet_train-api (LoadError)
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/dummy/config/application.rb:7:in `<top (required)>'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/dummy/config/environment.rb:2:in `require_relative'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/dummy/config/environment.rb:2:in `<top (required)>'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/test_helper.rb:4:in `require_relative'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/test_helper.rb:4:in `<top (required)>'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/lib/scaffolding/block_manipulator_test.rb:1:in `require'
	from /Users/gabriel_zayas/work/bt/bullet_train-super_scaffolding/test/lib/scaffolding/block_manipulator_test.rb:1:in `<top (required)>'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `each'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:47:in `load_tests'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/test_unit/runner.rb:40:in `run'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine/commands.rb:9:in `require'
	from /Users/gabriel_zayas/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.4/lib/rails/engine/commands.rb:9:in `<top (required)>'
	from bin/rails:14:in `require'
	from bin/rails:14:in `<main>'
```

**Comment by newstler** [comment]
@kaspth Can you please look at this? I'm not sure how that should be.

**Comment by kaspth** [comment]
@gazayas where did you put `gem "jbuilder"` in the Gemfile, before or after `jbuilder-schema`?

I think I removed the `require "jbuilder"` call under the assumption that people would do:

```ruby
# Gemfile
gem "jbuilder"
gem "jbuilder-schema"
```

…and then Bundler would've activated and required `Jbuilder` before `Jbuilder::Schema`.

**Comment by kaspth** [comment]
Nevermind, I could confirm the issue and shipped the proposed fix in https://github.com/bullet-train-co/jbuilder-schema/commit/b0b2270c4044202de90febc539be8e98899b9c79

**Comment by gazayas** [comment]
No problem, I also just confirmed that tests are passing in the gem, thank you!
